- name: install dep libs.
  shell: >
    apt-get -y install libbz2-dev;
- name: build.
  shell: >
    mkdir -p /opt/src;
    cd /opt/src;
    tar xzf tokyocabinet-1.4.45.tar.gz;
    cd /opt/src/tokyocabinet-1.4.45;
    ./configure;
    make;
    make install;
    cd /opt/src;
    tar xzf tokyotyrant-1.1.40.tar.gz;
    cd /opt/src/tokyotyrant-1.1.40;
    ./configure;
    make;
    make install;
